frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/form/EditUserProfile.tsx
frontend/src/configs/routes.tsx
frontend/src/features/auth/UserProfile.tsx
package-lock.json

ticket: [ERP-601](https://jira.seta-international.vn/browse/ERP-601)
Create UI for User profile

ERP-601 UI UserProfile

---

backend/app/api/tasks.py
backend/app/core/database.py
backend/app/models/tasks.py
backend/app/schemas/tasks.py
backend/app/services/tasks.py

Ticket : [ERP-640](https://jira.seta-international.vn/browse/ERP-640)
- Create query database for get tasks in services
- Add service task in api task
- Add routing task in main.py

ERP-640 : Create api for get tasks

---

backend/app/api/auth.py
backend/app/schemas/auth.py
backend/app/services/auth.py

- ticket: [ERP-615](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-615#)
- create login endpoint
- create method login in AuthService

ERP-615 build login api

---

backend/app/api/task.py
backend/app/middlewares/auth_middleware.py
backend/app/schemas/task.py
backend/app/services/task.py

- ticket: [ERP-611](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-611#)
- create auth middleware to verify token
- create 'create task' endpoint
- create TaskService and create method

ERP-611: build create task api

---

backend/app/api/task.py
backend/app/schemas/task.py
backend/app/services/task.py

- ticket: [ERP-613](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-613#)
- create update task endpoint
- create method update

ERP-613: build update task api

---

backend/app/api/task.py
backend/app/services/task.py

- ticket: [ERP-621](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-621#)
- create delete task endpoint
- add delete task method

ERP-621: build delete task api

---

backend/app/api/task.py
backend/app/services/task.py

- ticket: [ERP-607](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-607#)
- create get all task by user login endpoint
- create get_all_tasks_by_user method

ERP-607: build retrieving all task by user api

---

backend/app/api/task.py
backend/app/schemas/task.py
backend/app/services/task.py

- ticket: [ERP-609](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-609#)
- create get a task detail endpoint
- create get_one_task method

ERP-609: build get task detail api

---

backend/alembic.ini
backend/app/api/task.py
backend/app/models/task.py
backend/app/schemas/task.py
backend/app/services/task.py
backend/app/utils/enums.py

- ticket: [ERP-623](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-623#)
- create change task status endpoint
- create change_task_status method

ERP-623: build change task's status api

---

backend/app/api/auth.py
backend/app/schemas/auth.py
backend/app/services/auth.py

- ticket: [ERP-619](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-619#)
- create change password endpoint
- create change_password method

ERP-619: build change password api

---

frontend/src/app/services/api.ts
frontend/src/components/form/LoginForm.tsx
frontend/src/components/form/RegisterForm.tsx
frontend/src/features/auth/Login.tsx
frontend/src/types/Auth.ts

Ticket : [ERP-616](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-616#)
- create login screen
[login_screen](https://github.com/blueocvn/fullstack-todo-app/assets/169635654/9cf6725d-d980-47da-a514-c74e803c9136)
[validate_login](https://github.com/blueocvn/fullstack-todo-app/assets/169635654/22cd9168-08a4-40b8-b79a-475d36237775)

ERP-616 Create Login Screen

---

frontend/src/App.tsx
frontend/src/app/services/api.ts
frontend/src/components/form/LoginForm.tsx
frontend/src/components/form/RegisterForm.tsx
frontend/src/components/form/ResetPasswordForm.tsx
frontend/src/features/auth/Login.tsx
frontend/src/features/auth/ResetPassword.tsx
frontend/src/types/Auth.ts

Ticket : [ERP-620](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-620#)
- create password reset screen

ERP-620 Create password reset screen

---

backend/app/api/auth.py
backend/app/models/user.py
backend/app/schemas/auth.py
frontend/src/components/header/Header.tsx

Sửa lại tên các cột trong model user để khớp với tên cột dưới database

fix(userModel): Change the columns name to

---

frontend/src/app/services/api.ts
frontend/src/app/store.ts
frontend/src/components/layouts/hocs/withAppHeader.tsx
frontend/src/features/HomePage/index.tsx
frontend/src/types/Task.ts

Ticket : [ERP-643](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-643#)
- create all tasks for a person screen

ERP-643 Create all tasks for a person screen

---

backend/app/api/auth.py
backend/app/api/tasks.py
backend/app/schemas/auth.py
backend/app/schemas/tasks.py
backend/app/services/auth.py
frontend/src/App.tsx
frontend/src/components/form/ChangePasswordFrom.tsx
frontend/src/components/header/Header.tsx

Lấy dữ liệu người dùng và tự gắn tên vào UI
Lúc trước chưa có hàm lấy dữ liệu và tên người dùng được gắn tĩnh vào ui
Bổ sung thêm hàm lấy dữ liệu bằng axios và để tên người dùng đổi theo dữ liệu lấy được

ERP-578: Lấy dữ liệu người dùng và tự gắn tên vào UI

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/NotFound.tsx
frontend/src/components/form/RegisterForm.tsx
frontend/src/components/form/TaskAddForm.tsx
frontend/src/components/layouts/PrivateOutlet.tsx
frontend/src/components/task/TaskTable.tsx
frontend/src/configs/routes.tsx
frontend/src/features/task/TaskAdd.tsx
frontend/src/interfaces/form.ts

Ticket: [ERP-635](https://jira.seta-international.vn/browse/ERP-635)
- Import component flowbite for create form
- Using yup for validation data
- Using dayjs for format date

ERP-635: Create ui for create task

---

frontend/src/app/services/api.ts
frontend/src/features/HomePage/index.tsx
frontend/src/types/Task.ts

Ticket : [ERP-644](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-644#)
-create a new task for a person screen

ERP-644 Create a new task for a person screen

---

backend/app/api/auth.py
backend/app/services/auth.py
frontend/src/App.tsx

Change how get email function work
Old get email function make some conflict
Remove conflict code

ERP-578: fix(auth services)

---

backend/alembic.ini
backend/app/api/auth.py
backend/app/api/tasks.py
backend/app/core/config.py
backend/app/core/database.py
backend/app/services/auth.py
backend/poetry.lock
backend/pyproject.toml

Adding .env and make code work with it
Different postgresURI between team members make unwanted error
Edit code and make it use data from .env file

ERP-647: Add and change file to work with .env

---

backend/app/api/task.py
frontend/src/app/services/api.ts
frontend/src/features/HomePage/index.tsx
frontend/src/types/Task.ts

Ticket : [ERP-648](https://jira.seta-international.vn/secure/RapidBoard.jspa?rapidView=6&projectKey=ERP&view=detail&selectedIssue=ERP-648#)
- Delete task for a person

ERP-648 Delete task for a person

---

frontend/src/app/services/api.ts
frontend/src/app/services/task.ts
frontend/src/app/store.ts
frontend/src/components/form/LoginForm.tsx
frontend/src/components/form/RegisterForm.tsx
frontend/src/components/header/Header.tsx
frontend/src/components/header/UserDropdown.tsx
frontend/src/components/task/TaskTable.tsx
frontend/src/features/auth/Login.tsx
frontend/src/features/auth/Register.tsx
frontend/src/features/task/TaskList.tsx
frontend/src/interfaces/route.ts
frontend/src/interfaces/task.ts
frontend/src/interfaces/user.tsx

Ticket: [ERP-641](https://jira.seta-international.vn/browse/ERP-641)
- Using rtk query to get api /api/tasks
- Display data to task table with prop

ERP-641: Connect api with frontend for display tasks

---

frontend/src/App.tsx
frontend/src/components/modal/TaskEditModal.tsx
frontend/src/components/task/TaskTable.tsx
frontend/src/interfaces/form.ts

Ticket: [ERP-639](https://jira.seta-international.vn/browse/ERP-639)
- Create ui from by Flowbite-react
- Using react-hook-form for submit data
- Using yup for validation data

ERP-600(feat): create ui for edit task

---

backend/app/api/team.py
frontend/src/app/services/api.ts
frontend/src/components/home/EditModal.tsx
frontend/src/components/team/AddTaskModal.tsx
frontend/src/components/team/deleteTeamModal.tsx
frontend/src/features/HomePage/index.tsx
frontend/src/features/TeamPage/TaskDetailPage.tsx
frontend/src/features/TeamPage/TeamDetailPage.tsx
frontend/src/features/TeamPage/TeamPage.tsx
frontend/src/features/auth/Login.tsx

update team feature and fix bug

feat: update and fix bug

---

backend/app/api/tasks.py
backend/app/services/tasks.py

Ticket: [ERP-652](https://jira.seta-international.vn/browse/ERP-652)

ERP-652(feat): Create api for delete task
